### ISSUE TITLE
`window.qrypto.account` showing logged in when Qrypto is logged out

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/qrypto#161]
![image](https://user-images.githubusercontent.com/4350404/45610663-f1358280-ba86-11e8-8b24-d47c12044693.png)

**Comment by soshochang** [comment]
-window.qrypto.account will only show as logged in if you are logged into a specific wallet account(not just the master qrypto account)
-this is intentional because if the user is not logged into a specific account, there is no wallet address to provide, and is effectively not "logged in" 
- I can add something to the readme  to clarify this, unless you want me to change the behavior?

**Comment by dwalintukan** [comment]
#163
