### ISSUE TITLE
Wallet Import Hangs with Wrong Private Key

### ISSUE THREAD

**Issue by JB395** [bodhiproject/qrypto#171]
The wallet import process will hang on the “Loading…” animation if a private key from the wrong blockchain is used in the sequence:

(MainNet) CREATE NEW WALLET – IMPORT WALLET – Private Key - enter TestNet private key - IMPORT:

![wallet hangs](https://user-images.githubusercontent.com/29760787/46033644-ae019200-c0cc-11e8-96b5-3410481de479.jpg)

**Comment by soshochang** [comment]
@JB395, Thank you for the report. 
When I try to import a testnet private key for mainnet I get a popup dialog stating "Invalid Network". I believe you may have been using an earlier version of the app where we were not handling the error. Please let me know if you're still having this error otherwise I will consider this issue resolved.
