### ISSUE TITLE
getInfo polling result is not updating window.qrypto

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/qrypto#176]
After the initial login with qrypto, I dont seem to be getting the `window.qrypto.account has been updated message`. See the below image, after many minutes, no new messages.

![image](https://user-images.githubusercontent.com/4350404/46057869-1a8a9880-c182-11e8-8abe-2d37ec2a06ff.png)

**Comment by soshochang** [comment]
can you check if you are using 1.4.1?

**Comment by soshochang** [comment]
resolved in PR173
Note:
-the "account has been updated message" will only get sent if there is a _change_ in the account and not on every interval of the polling. So to see this message, the user would have to send or receive QTUM  and the transaction would have to get confirmed.
-what PR173 does is make it so that the account polling  continues while the pop-up window is closed(but qrypto is still running in the background, and the user is still logged in), previously the polling stopped as soon the popup window was closed.

**Comment by dwalintukan** [comment]
:+1: I wonder if this is bad practice for those who are not using the wallet for dapps...
