### ISSUE TITLE
Error for trying to send more than you have does not bubble down 

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/qrypto#189]
Example:
- wallet has 1 qtum
- from dapp: trying to bet 0.999 qtum
- this tx will fail since we dont have enough qtum for the bet + tx 

The error message returned from Qrypto is a `400 error code`. We need to return the error message down the call chain so that the dapp can accurately get the reason why the tx is failing, e.g. "Not enough QTUM to send this transaction", etc etc.

This also happens when doing a regular qtum send:
![image](https://user-images.githubusercontent.com/4350404/46331594-caf51280-c642-11e8-9935-4e45f4f05d95.png)

I'm guessing the qtumjs-wallet does not return the error message? Or we are not handling the error message properly.

**Comment by soshochang** [comment]
Hi Deric, this is kind of strange, because I get a different error message when I tried to send a max balance transaction. Can you try it again on your end and see what you get? 
In the meantime I will work on sending the error to the dapp

![screen shot 2018-10-05 at 11 51 35 am](https://user-images.githubusercontent.com/4063649/46554461-29193400-c895-11e8-8aae-f984272f0221.png)

**Comment by dwalintukan** [comment]
The case that gave us the error message is when say you have 0.9 QTUM and you try to send like 0.7 QTUM and its not enough to pay the fee. Bernard discovered this while testing with very little QTUM.

One of the main issues is that by the time the error ends up at the web app, the error message is very basic and does not explain anything. Just returns a 400 I believe.

Ask Bernard the steps he took to repro this, but it should be something like:
1. start a new wallet
2. send that wallet like 0.9 QTUM
3. try to do a bet for 0.7 or 0.8 QTUM
4. you will see the error

**Comment by soshochang** [comment]
resolved PR193
